pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url = "https://nexus.inductiveautomation.com/repository/public" 
        }
    }
}

rootProject.name = "mustry-solutions-perspective-components"

dependencyResolutionManagement {
    repositories {
        // enable resolving dependencies from the inductive automation artifact repository
        maven {
            url "https://nexus.inductiveautomation.com/repository/public"
        }
        mavenCentral()
    }
}

include(
":",
    ":common",
    ":gateway",
    ":designer",
    ":web"
)
